name: Node CI
on: [push, pull_request]
jobs:
  node-build:
    name: Install, lint, build and test
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
      - run: pnpm install --frozen-lockfile
      - run: pnpm lint
      - run: pnpm build
